spring:
  application:
    name: Employee Management System
  datasource:
    url: jdbc:postgresql://localhost:5432/db_employee
    username: postgres
    password: whynot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true

security:
  jwt:
    secret-key: 8FDBDA95196C7B0B18D5335D979F406A6C4721315A801C6332D09DBD5F633AB0
    expiration-time: 3600000

logging:
  level:
    web: debug
    org:
      springframework:
        aop: debug

